<?php

namespace PhpBrew\Tests\Tasks;

use CLIFramework\Logger;
use GetOptionKit\OptionResult;
use PhpBrew\Buildable;
use PhpBrew\Tasks\MakeTask;
use PHPUnit\Framework\TestCase;

/**
 * @small
 * @internal
 */
class MakeTaskTest extends TestCase
{
    private $make;

    public function createLogger()
    {
        $logger = new Logger();
        $logger->setQuiet();

        return $logger;
    }

    protected function setUp(): void
    {
        $this->make = new MakeTask($this->createLogger(), new OptionResult());
        $this->make->setQuiet();
    }

    public function test_make_install(): void
    {
        self::assertTrue($this->make->install(new MakeTaskTestBuild()));
    }

    public function test_make_clean(): void
    {
        self::assertTrue($this->make->clean(new MakeTaskTestBuild()));
    }

    public function test_run_with_valid_target(): void
    {
        $build = new MakeTaskTestBuild();
        self::assertTrue($this->make->run($build));
    }

    public function test_when_there_is_no_makefile(): void
    {
        // ignores error messages generated by make command
        ob_start();
        self::assertFalse($this->make->install(new MakeTaskTestNoSuchFileBuild()));
        ob_end_clean();
    }

    public function test_set_quiet(): void
    {
        $make = new MakeTask($this->createLogger(), new OptionResult());

        self::assertFalse($make->isQuiet());

        $make->setQuiet();

        self::assertTrue($make->isQuiet());
    }
}

class MakeTaskTestBuild implements Buildable
{
    public function getSourceDirectory()
    {
        return __DIR__ . '/../../fixtures/make/';
    }

    public function getBuildLogPath()
    {
        return null;
    }

    public function isBuildable()
    {
        return true;
    }
}

class MakeTaskTestNoSuchFileBuild implements Buildable
{
    public function getSourceDirectory()
    {
        return __DIR__ . '/../../fixtures/make/dummy';
    }

    public function getBuildLogPath()
    {
        return null;
    }

    public function isBuildable()
    {
        return false;
    }
}
